callback_url: https://708e-2603-6010-c600-3a68-3521-9b78-b843-531f.ngrok-free.app/webhook
servers:
  - name: :provider1
    url: https://mock-text-provider.parentsquare.com/provider1
    score: 30
  - name: :provider2
    url: https://mock-text-provider.parentsquare.com/provider2
    score: 70