callback_url: https://parent-square.herokuapp.com/webhook
servers:
  - name: :provider1
    url: https://mock-text-provider.parentsquare.com/provider1
    score: 30
  - name: :provider2
    url: https://mock-text-provider.parentsquare.com/provider2
    score: 70